---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: chaospod
  name: chaospodsa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: chaospod
  name: chaospod
rules:
  - apiGroups:
      - "apps"
      - "v1"
    resources:
      - "pods"
      - "deployments/scale"
    verbs:
      - list
      - delete
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: chaospod
  name: chaospod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chaospod
subjects:
  - kind: ServiceAccount
    name: chaospodsa
---
