name: ci

on:
  push:
  workflow_dispatch:
    inputs:
      run-test:
        required: false
        description: "trigger pipeline whenever I want"
        default: "test"
env:
  GO_VERSION: 1.19

jobs:
  simple_ci:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        # add alternative platforms here e.g. windows if the build is required on a different platform as well as a linux distro
        os: [ubuntu-latest]
    outputs:
      test_result: ${{ steps.test_package.outcome }}
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: golangci-lint
        continue-on-error: true
        id: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
      - name: run vet
        id: vet
        if: matrix.os == 'ubuntu-latest'
        run: go vet -mod=readonly ./...
      - name: test
        continue-on-error: false
        id: test_application
        run: go test -mod=readonly ./...
